language: csharp
solution: solution-name.sln
script:    # the following commands are just examples, use whatever your build process requires
   - xbuild /p:Configuration=Release {"PortalSicoobDivicred.sln"}
  
